Lesson 7 Homework
Jarchik/PyLessons pull request #6
Opened 2023-05-21 15:34 UTC by Jarchik

2023-05-24 06:53 UTC, idegtiarov requested changes

2023-05-24 06:53 UTC, idegtiarov commented on lesson_7/school/diary/templates/weekday.html
> +                <li><a href="/day/{{ week_day.id }}/note/{{ note.id }}">{{ note.title }}</a></li>
It would be better to use URL tag instead of direct url constructing.

2023-05-24 06:53 UTC, idegtiarov commented on lesson_7/school/diary/views.py
> +    weekday = get_object_or_404(WeekDay, pk=day_id)
This step is redundant since within Note object we always have a direct link to the WeekDay object through ForeignKey connection.

We even could change the URL and omit redundant day_id from it

```
path("note/<int:note_id>/", views.my_note, name="my_note"),
```

2023-05-28 12:29 UTC, Jarchik commented on lesson_7/school/diary/views.py
> +    weekday = get_object_or_404(WeekDay, pk=day_id)
Oh. You are right. Thank. Fixed in homework_8

2023-05-28 12:35 UTC, merged